name: RPGCraft
version: 0.8.5
author: Michael Rhodes
website: http://tigerstudios.net/rpgcraft
main: net.tigerstudios.RPGCraft.RPGCraft
depend: []

commands:
    rpg:
        description: 
        usage: Type /rpg help for usage instructions
    bal:
        description: Retrieve your currency balance
        usage: /bal
        permission: rpgcraft.money
    balance:
        description: Retreive your currency balance
        usage: /balance
        permission: rpgcraft.money
    deposit:
        description: Deposit money into the bank
        usage: /deposit <gold> <silver> <copper>
        permission: rpgcraft.money
    withdraw:
        description: Withdraw coins from your rpg account
        usage: /withdraw <gold> <silver> <copper>
        permission: rpgcraft.money
