name: RPGCraft
version: 0.7.0
author: Michael Rhodes
website: http://tigerstudios.net/minecraft
main: net.tigerstudios.RPGCraft.RPGCraft
depend: [Spout]

commands:
    rpg:
        description: 
        usage: Type /rpg help for usage instructions
    bal:
        description: Retreive your currency balance
        usage: /bal
        permission: rpgcraft.money
    balance:
        description: Retreive your currency balance
        usage: /balance
    deposit:
        description: Deposit money into the bank
        usage: /deposit <gold> <silver> <copper>
        permission: rpgcraft.money
    withdraw:
        description: Withdraw coins from your rpg account
        usage: /withdrawl <gold> <silver> <copper>
        permission: rpgcraft.money